print("Makarész Dominik")

print("==================================")
print("||                              ||")
print("|| Nagy József                  ||")
print("||                              ||")
print("|| 15A                          ||")
print("||                              ||")
print("|| 2012.01.04                   ||")
print("||                              ||")
print("==================================")
